repos:
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.2.0
    hooks:
    -   id: tofu_fmt
        files: \.(tf|tofu)(vars)?$
        exclude: \.terraform\/.*$
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
    -   id: gitleaks